--- #ansible-playbook ec2_deploy.yml  --extra-vars="region=eu-west-1"
- name: Terminate ec2 instances
  hosts: localhost
  vars_files:
    - regions/{{ region }}.yml
  tasks:
    - name: Terminate instance
      ec2:
        key_name: "{{ key_name }}"
        assign_public_ip: yes
        instance_type: "{{ instance_type }}"
        region: "{{ region }}"
        image: "{{ image }}" 
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        count : "{{ count }}"
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'
